### ISSUE TITLE
Add bslib to DESCRIPTION?

### ISSUE THREAD

**Issue by jsta** [djnavarro/bs4cards#32]
Perhaps I got the yaml header syntax wrong or there's something misconfigured in my R installation, but I needed to install the [bslib](https://github.com/rstudio/bslib) package or rmarkdown complained that I was passing an input to the yaml header `theme`.

**Comment by djnavarro** [comment]
That's a good thought. I might add it as a suggested package. The bs4cards package doesn't technically depend on bslib, but the vast majority of use cases would probably be using the rmarkdown html_document output format, and you do need bslib to make boostrap 4 available in that case. Thanks! I'll address this next time I return to the package!
